import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Flex, Heading, Text, Link, Code } from "@chakra-ui/react";
import ChatInterface from "@/components/ChatInterface";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*  */}
      <Flex direction="column" align="center" justify="center" h="100vh">
        <Heading as="h1" size="2xl" mb={4}>
          FitHub
        </Heading>
        <Text fontSize="xl" mt={4}>
          {`Welcome to FitHub, your personal fitness assistant. Let's get started!`}
        </Text>
        <ChatInterface />
      </Flex>
    </>
  );
}
